name: Run tests

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          # Install a specific version of uv.
          version: "0.11.3"

      - name: Check out herald_crawler
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: |
          uv run pytest
